version: '3.9'
services:

  web:
    build:
      context: .
      dockerfile: ./docker/debian/Dockerfile
      args:
        - DOCKER_BUILD_DEBIAN_VERSION=${DOCKER_BUILD_DEBIAN_VERSION}
    container_name: ${DOCKER_WEB_CONTAINER_NAME}
    volumes:
      # Volume definition format => local path:path in container
      # For laravel, this docker-compose.yml should be located in the root directory
      - .:/var/www/html
      # Preconfigured php.ini file should be in the `docker/php` folder
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      # local port (i.e. localhost:8000): port in container
      - ${DOCKER_WEB_PORT_NUMBER}:80

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - DOCKER_BUILD_MYSQL_VERSION=${DOCKER_BUILD_MYSQL_VERSION}
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: always
    ports:
      - 3306:3306
